

# [networks.contracts]
# weth = {abi = "abis/weth.json"}
# usdc = {abi = "abis/usdc.json"}
# aavev3_pool_address_provider = {abi = "abis/aavev3_pool_address_provider.json"}
# pool = { abi = "abis/pool.json" }
# aave_protocol_data_provider = { abi = "abis/aave_protocol_data_provider.json" }
# eth_usd = { abi = "abis/eth_usd.json" }
# usdc_usd = { abi = "abis/usdc_usd.json" }
# uniswap_swap_router = { abi = "abis/uniswap_swap_router.json" }


# [project]
# src = "src"
# out = "out"
# dot_env = ".env"
# save_abi_paths = "abis"
# default_network_name = "eth-forked"

# [networks.eth-forked]
# fork = true
# url = "$MAINNET_RPC_URL"
# default_account_name = "anvil1"

# [networks.eth-forked.contracts]
# weth = { address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2" }
# usdc = { address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48" }
# aavev3_pool_address_provider = { address = "0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e" }
# aave_protocol_data_provider = { address = "0x0a16f2FCC0D44FaE41cc54e079281D84A363bECD" }
# eth_usd = { address = "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"}
# usdc_usd = { address = "0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6" }
# uniswap_swap_router = { address = "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45" }


[project]
src = "src"
out = "out"
dot_env = ".env"
save_abi_paths = "abis"

# -----------------------------
# Shared Contract ABIs
# -----------------------------
[networks.contracts]
weth = { abi = "abis/weth.json" }
usdc = { abi = "abis/usdc.json" }

aavev3_pool_address_provider = { abi = "abis/aavev3_pool_address_provider.json" }
aave_protocol_data_provider = { abi = "abis/aave_protocol_data_provider.json" }
pool = { abi = "abis/pool.json" }

eth_usd = { abi = "abis/eth_usd.json" }
usdc_usd = { abi = "abis/usdc_usd.json" }

uniswap_swap_router = { abi = "abis/uniswap_swap_router.json" }
uniswap_v3_pool = { abi = "abis/uniswap_v3_pool.json" }


# -----------------------------
# Tenderly Virtual Network
# -----------------------------
[networks.tenderly]
url = "https://virtual.mainnet.eu.rpc.tenderly.co/5db9b449-3a60-4c5d-b8de-ff8415cb3263"
chain_id = 1
fork = false
default_account_name = "anvil1"


# -----------------------------
# Tenderly Contract Addresses
# -----------------------------
[networks.tenderly.contracts]
weth = { address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2" }
usdc = { address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48" }

aavev3_pool_address_provider = { address = "0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e" }
aave_protocol_data_provider = { address = "0x0a16f2FCC0D44FaE41cc54e079281D84A363bECD" }

eth_usd = { address = "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419" }
usdc_usd = { address = "0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6" }

uniswap_swap_router = { address = "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45" }

# Uniswap V3 WETH/USDC 0.3% Pool
uniswap_v3_pool = { address = "0x8ad599c3A0ff1De082011EFDDc58f1908eb6e6D8" }
