[project]
src = "src"
out = "out"
dot_env = ".env"
save_abi_paths = "abis"

[networks.contracts]
weth = {address = "abis/weth.json"}

[networks.eth-forked]
forked = true
url = "$MAINNET_RPC_URL"
default_account_name = "anvil1"
unsafe_password_file = "$ANVIL1_PASSWORD_FILE"

[networks.eth-forked.contracts]
usdc = {address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"}
weth = {address =  "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"}